[package]
name = "mujoco_rs"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
glfw = "0.59.0"

[build-dependencies]
bindgen = "0.71.1"
