[package]
name = "fuzbai_simulator"
version = "3.7.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = {version = "0.24.2", features = ["extension-module", "abi3-py38"]}
agent_rust = {path = "../fuzbai-agent/"}
rand = "0.9.1"
mujoco-rs = "2.1.1"

[build-dependencies]
mujoco-rs = "2.1.1"


[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"
