[package]
name = "fuzbai_simulator"
version = "3.5.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = "0.24.2"
mujoco_rs = {path = "../mujoco_rust/"}
agent_rust = {path = "../fuzbai-agent/"}
rand = "0.9.1"
glfw = "0.59.0"

[build-dependencies]
mujoco_rs = {path = "../mujoco_rust/"}

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"
