[build-system]
requires = ["maturin>=1.1,<2.0"]
build-backend = "maturin"

[project]
name = "fuzbai_simulator"
version = "3.1"
requires-python = ">=3.11"
authors = [
  {name = "David Hožič", email = "davidhozic@gmail.com"},
  {name = "Matevž Bošnak"},
]
readme="../README.md"
keywords=["python", "rust", "reinforcement learning", "simulation", "mujoco", "table-football"]
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Rust",
]

[project.urls]
Repository = "https://github.com/davidhozic/fuzbai-simulation"

[tool.maturin]
features = ["pyo3/abi3-py38", "pyo3/extension-module", "pyo3/generate-import-lib"]
include = ["../mujoco_rust/lib/*.so"]
bindings = "pyo3"
compatibility = "manylinux_2_34"
